```python
def test_create_superuser(self):
        """Test creating a superuser"""
        user = get_user_model().objects.create_superuser(
            'test@example.com',
            'test111',
        )

        self.assertTrue(user.is_superuser)
        self.assertTrue(user.is_staff)
```

```bash
$ docker-compose run --rm app sh -c "python manage.py test"
[+] Running 1/0
 - Container api-prac-db-1  Running                                      0.0s 
Creating test database for alias 'default'...
System check identified no issues (0 silenced).
E.....Waitng for database ...
Database unvailable, waiting 1 second ...
Database unvailable, waiting 1 second ...
Database unvailable, waiting 1 second ...
Database unvailable, waiting 1 second ...
Database unvailable, waiting 1 second ...
Database available !
.Waitng for database ...
Database available !
.
======================================================================        
ERROR: test_create_superuser (core.tests.test_models.ModelTests)
Test creating a superuser
----------------------------------------------------------------------        
Traceback (most recent call last):
  File "/app/core/tests/test_models.py", line 41, in test_create_superuser    
    user = get_user_model().objects.create_superuser(
AttributeError: 'UserManager' object has no attribute 'create_superuser'      

----------------------------------------------------------------------        
Ran 8 tests in 0.455s

FAILED (errors=1)
Destroying test database for alias 'default'...

docker-compose run --rm app sh -c "python manage.py createsuperuser"

```